# Generated by Django 2.2 on 2021-06-28 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.CharField(default=1, max_length=500, verbose_name='Imagen link'),
            preserve_default=False,
        ),
    ]
