# Generated by Django 2.2 on 2021-06-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cuerpo',
            field=models.TextField(verbose_name='Descripcion'),
        ),
    ]
