# Generated by Django 2.2 on 2021-06-29 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210628_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='genero',
            field=models.IntegerField(choices=[(1, 'Accion'), (2, 'Terror'), (3, 'Infantil'), (4, 'Romanticas'), (5, 'Musicales')], default=1),
        ),
    ]
